#!/bin/bash

buffer=$(git ls-remote 'https://gitlab.freedesktop.org/NetworkManager/NetworkManager.git' 'refs/tags/*')

pkgver=$(sed 's|^.*refs/tags/||g' <<< "$buffer" | \
  sed -r -e '/^[0-9]/!d' -e '/-(dev|rc|alpha|beta|stable|unstable)/d' -e '/[0-9]*$/!d' | \
  sort --version-sort | tail -1)

commit=$(awk '($2 ~ /'${pkgver}'\^\{\}$/) {print $1}' <<< "$buffer")
pppver=$(LC_MESSAGES=C pacman -Si ppp | awk -F ' *: *' '/^Version/ {print $2}' | sed 's/-[0-9]*$//')

setconf PKGBUILD pkgver $pkgver
setconf PKGBUILD _commit=${commit}"   # tags/${pkgver}^{}"
setconf PKGBUILD _pppver=${pppver}

mkpkg --verifysource -f
mkpkg --srcinfo

branch=$(git rev-parse --abbrev-ref HEAD)

if mkpkg -sicfr --noconfirm; then
  git add PKGBUILD .SRCINFO
  mtime=$(date +%s)
  (( mtime % 2 )) && (( mtime-- ))
  git commit --date=$(date -d @$mtime +%Y-%m-%dT%H:%M:%S) -m 'Build version '${pkgver}
  git push -u origin $branch
  git tag --annotate -m ${pkgver} v${pkgver}
  git push --tags -q -u origin $branch
fi

exit $?

# vim: ft=sh ts=2 sts=2 sw=2 et:
